language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t arnoldmachado/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true arnoldmachado/docker-react npm run test

deploy:
  provider: eleasticbeanstalk
  region: 'ap-south-1'
  app: 'docker'
  env: 'Docker-env'
  bucket_name: 'elasticbeanstalk-ap-south-1-207448959310'
  bucket_path: 'docker'
  on: 
    branches:
      only:
        - master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
